db:
  pg_db_url: "postgres://postgres:hetu@0.0.0.0:5432"
  pg_db_name: "operator_db"
  max_connect_pool: 30
  min_connect_pool: 10
  connect_timeout: 30
  acquire_timeout: 60
net:
  rest_url: "0.0.0.0:8080"
  outer_url: "http://127.0.0.1:8080"
  dispatcher_url: "http://127.0.0.2:3000"
  tee_llm_cid: 15
  tee_llm_port: 5005
node:
  node_id: "0x02a5592a6de1568f6efdc536da3ef887f98414cb"
  signer_key: "77f4b2fbf3f32687f03d84d323bd5cb443f53b0fc338b51c24e319a520c87217"
  cache_msg_maximum: 500
  heartbeat_interval: 10
  ai_models:
    - "llama-2-7b-chat.Q4_0.gguf"
chain:
  chain_rpc_url: "https://rpc.holesky.ethpandaops.io"
  vrf_range_contract: "0x0a24a30E5a8Ca9B790c7f57F0826159569e8dc4B"
  vrf_sort_precision: 6
api:
  read_maximum: 20